"use client";

import { useEffect, useMemo, useState } from "react";

type Module = { id: number; title: string; subtitle: string; practice: string; lessons: string[]; topics: [string, string][] };
const modules: Module[] = [
  { id: 1, title: "Ambiente e fundamentos", subtitle: "Windows, PowerShell, WSL 2 e primeiros containers.", practice: "Execute hello-world e registre a mensagem de sucesso no seu checklist.", lessons: ["Preparar Windows e WSL 2", "Conhecer Docker Desktop", "Imagem, container e registry"], topics: [["WSL 2", "permite usar um ambiente Linux integrado ao Windows"], ["Docker Desktop", "fornece o motor que cria e executa containers no Windows"], ["imagem Docker", "é um molde imutável para criar containers"], ["container", "é uma instância em execução de uma imagem"], ["docker run", "cria e inicia um container a partir de uma imagem"], ["Docker Hub", "é um registry que hospeda imagens"], ["PowerShell", "é o terminal recomendado para estes exercícios no Windows"], ["docker ps", "lista containers que estão em execução"], ["porta publicada", "conecta uma porta do computador a uma porta do container"], ["hello-world", "é uma imagem pequena para confirmar que Docker está funcionando"]] },
  { id: 2, title: "Docker na prática", subtitle: "Portas, logs, ciclo de vida e Dockerfile.", practice: "Containerize uma aplicação simples e abra-a em localhost.", lessons: ["Executar e parar containers", "Ler logs e entrar no terminal", "Criar imagens com Dockerfile"], topics: [["-d", "deixa o container rodando em segundo plano"], ["docker logs", "mostra a saída produzida pelo container"], ["docker stop", "interrompe um container em execução"], ["Dockerfile", "descreve como montar uma imagem"], ["WORKDIR", "define a pasta de trabalho dentro da imagem"], ["COPY", "leva arquivos do projeto para a imagem"], ["CMD", "define o comando padrão ao iniciar o container"], ["docker build", "cria uma imagem a partir do Dockerfile"], ["-p 3000:3000", "publica a porta 3000 do container na porta 3000 do computador"], ["tag", "identifica uma versão de imagem, como minha-app:1.0"]] },
  { id: 3, title: "Aplicações com Docker", subtitle: "Volumes, redes, banco de dados e Docker Compose.", practice: "Suba uma API e PostgreSQL usando compose.yaml.", lessons: ["Persistir dados com volumes", "Conectar serviços por rede", "Orquestrar com Compose"], topics: [["volume nomeado", "mantém dados mesmo após remover um container"], ["bind mount", "compartilha uma pasta do computador com o container"], ["rede Docker", "permite que containers conversem por nome"], ["localhost no container", "aponta para o próprio container"], ["compose.yaml", "declara os serviços de uma aplicação"], ["docker compose up", "cria e inicia os serviços declarados"], ["depends_on", "organiza a ordem de início entre serviços"], ["environment", "define variáveis de ambiente para um serviço"], ["docker compose down", "para e remove os containers do projeto"], [".dockerignore", "evita enviar arquivos desnecessários ao build"]] },
  { id: 4, title: "Fundamentos de Kubernetes", subtitle: "Kind, kubectl, Pods, Deployments e labels.", practice: "Crie um cluster Kind e implante uma app com duas réplicas.", lessons: ["Criar cluster local", "Declarar Pods e Deployments", "Usar labels e réplicas"], topics: [["Kind", "cria um cluster Kubernetes local usando Docker"], ["kubectl", "é a ferramenta de linha de comando para controlar o cluster"], ["node", "executa Pods dentro do cluster"], ["Pod", "é a menor unidade de execução do Kubernetes"], ["Deployment", "mantém a quantidade desejada de Pods"], ["replicas", "define quantas cópias da aplicação devem existir"], ["label", "é uma etiqueta usada para identificar recursos"], ["kubectl apply", "cria ou atualiza recursos declarados em YAML"], ["kubectl get pods", "lista os Pods do namespace atual"], ["YAML", "usa indentação com espaços para organizar configurações"]] },
  { id: 5, title: "Kubernetes em operação", subtitle: "Services, configuração, escala, saúde e atualizações.", practice: "Publique uma app, escale para três réplicas e execute um rollout.", lessons: ["Conectar com Services", "Configurar e proteger", "Escalar e observar"], topics: [["Service", "fornece um endereço estável para acessar Pods"], ["selector", "liga um Service aos Pods com labels correspondentes"], ["ConfigMap", "guarda configurações não sensíveis"], ["Secret", "guarda valores sensíveis que não devem ir para o código"], ["readiness probe", "define quando um Pod pode receber tráfego"], ["liveness probe", "detecta quando um container precisa reiniciar"], ["requests", "reservam recursos mínimos para um container"], ["limits", "definem o máximo de recursos que um container pode usar"], ["rollout", "atualiza uma versão gradualmente"], ["kubectl scale", "altera a quantidade de réplicas de um Deployment"]] },
  { id: 6, title: "Publicação e projeto final", subtitle: "Ingress, persistência, Helm, segurança e entrega.", practice: "Conclua o checklist do projeto final: app, banco, Compose e Kubernetes.", lessons: ["Publicar com Ingress", "Persistir dados", "Empacotar com Helm"], topics: [["Ingress", "declara regras para receber tráfego HTTP e enviá-lo a Services"], ["controller de Ingress", "executa as regras definidas pelo Ingress"], ["PersistentVolumeClaim", "solicita armazenamento persistente para uma aplicação"], ["StatefulSet", "é indicado quando réplicas precisam de identidade estável"], ["Helm", "instala pacotes configuráveis chamados charts"], ["chart", "é um pacote de recursos Kubernetes"], ["release", "é uma instalação de um chart no cluster"], ["namespace", "separa recursos dentro de um cluster"], ["RBAC", "controla quem pode executar ações no Kubernetes"], ["projeto final", "reúne Docker, Compose e Kubernetes em uma entrega prática"]] },
];

export default function Home() {
  const [active, setActive] = useState(1); const [progress, setProgress] = useState<number[]>([]); const [practice, setPractice] = useState<number[]>([]); const [answers, setAnswers] = useState<Record<number, number>>({}); const [attempts, setAttempts] = useState<Record<number, number[]>>({}); const [signedIn, setSignedIn] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("container-lab-v2"); if (saved) { const s = JSON.parse(saved); setProgress(s.progress || []); setPractice(s.practice || []); setAttempts(s.attempts || {}); } }, []);
  useEffect(() => { localStorage.setItem("container-lab-v2", JSON.stringify({ progress, practice, attempts })); }, [progress, practice, attempts]);
  const module = modules[active - 1]; const unlocked = active === 1 || attempts[active - 1]?.some(score => score >= 70);
  const score = useMemo(() => module.topics.reduce((sum, _, i) => sum + (answers[i] === 0 ? 10 : 0), 0), [answers, module]);
  const completeAssessment = () => { setAttempts(prev => ({ ...prev, [active]: [...(prev[active] || []), score] })); setAnswers({}); };
  const passed = attempts[active]?.some(s => s >= 70); const overall = Math.round((attempts && modules.filter(m => attempts[m.id]?.some(s => s >= 70)).length / modules.length) * 100);
  return <main><header><a className="brand">&gt;_ container<span>lab</span></a><nav><a href="#trilha">Trilha</a><a href="#perfil">Perfil</a></nav><button className="login" onClick={() => setSignedIn(!signedIn)}>{signedIn ? "Conta de estudo" : "Entrar para salvar"}</button></header><section className="hero"><p className="eyebrow">CURSO PRÁTICO PARA WINDOWS</p><h1>Aprenda Docker e Kubernetes <em>fazendo.</em></h1><p>Seis módulos guiados, práticas reais e avaliações para provar que você entendeu antes de avançar.</p><a className="cta" href="#trilha">Começar a trilha</a></section><section id="perfil" className="profile"><div><p className="eyebrow">SEU PROGRESSO</p><h2>{overall}% da trilha concluída</h2><p>{signedIn ? "Seu progresso está associado a esta conta de estudo." : "Entre para sincronizar seu progresso em todos os dispositivos."}</p></div><div className="badges">{modules.map(m => <span className={attempts[m.id]?.some(s => s >= 70) ? "badge earned" : "badge"} key={m.id}>M{m.id}</span>)}</div></section><section id="trilha" className="course"><aside>{modules.map(m => <button key={m.id} disabled={m.id > 1 && !attempts[m.id - 1]?.some(s => s >= 70)} className={active === m.id ? "module active" : "module"} onClick={() => setActive(m.id)}><b>Módulo {m.id}</b><span>{m.title}</span>{attempts[m.id]?.some(s => s >= 70) && <i>Aprovado</i>}</button>)}</aside><article className="lesson"><p className="eyebrow">MÓDULO {module.id} DE 6</p><h2>{module.title}</h2><p className="lead">{module.subtitle}</p><h3>O que você vai dominar</h3><ul>{module.lessons.map(x => <li key={x}>{x}</li>)}</ul><div className="practice"><h3>Laboratório prático</h3><p>{module.practice}</p><label><input type="checkbox" checked={practice.includes(active)} onChange={() => setPractice(p => p.includes(active) ? p.filter(x => x !== active) : [...p, active])}/> Concluí esta prática</label></div><h3>Avaliação do módulo</h3><p className="hint">Responda as 10 questões. Você precisa de 70% e concluir a prática para desbloquear o próximo módulo.</p>{module.topics.map(([topic, definition], i) => <fieldset key={topic}><legend>{i + 1}. Qual afirmação está correta sobre <strong>{topic}</strong>?</legend>{[definition, "é uma configuração que substitui qualquer outro recurso", "funciona apenas fora de containers"].map((choice, n) => <label key={choice}><input type="radio" name={`q${i}`} checked={answers[i] === n} onChange={() => setAnswers(a => ({ ...a, [i]: n }))}/>{choice}</label>)}</fieldset>)}<button className="cta" disabled={!practice.includes(active) || Object.keys(answers).length !== 10} onClick={completeAssessment}>Finalizar avaliação</button>{attempts[active]?.length > 0 && <div className={passed ? "result success" : "result"}><strong>Última nota: {attempts[active].at(-1)}%</strong><p>{passed ? "Módulo aprovado. A próxima etapa foi desbloqueada e sua badge foi concedida." : "Revise as aulas e tente novamente. As tentativas são ilimitadas."}</p></div>}</article></section></main>;
}
