"use client";

import { useEffect, useMemo, useState } from "react";

type Module = { id: number; title: string; subtitle: string; practice: string; lessons: string[]; topics: [string, string][] };
const modules: Module[] = [
  { id: 1, title: "Ambiente e fundamentos", subtitle: "Windows, PowerShell, WSL 2 e primeiros containers.", practice: "Execute hello-world e registre a mensagem de sucesso no seu checklist.", lessons: ["Preparar Windows e WSL 2", "Conhecer Docker Desktop", "Imagem, container e registry"], topics: [["WSL 2", "permite usar um ambiente Linux integrado ao Windows"], ["Docker Desktop", "fornece o motor que cria e executa containers no Windows"], ["imagem Docker", "� um molde imut�vel para criar containers"], ["container", "� uma inst�ncia em execu��o de uma imagem"], ["docker run", "cria e inicia um container a partir de uma imagem"], ["Docker Hub", "� um registry que hospeda imagens"], ["PowerShell", "� o terminal recomendado para estes exerc�cios no Windows"], ["docker ps", "lista containers que est�o em execu��o"], ["porta publicada", "conecta uma porta do computador a uma porta do container"], ["hello-world", "� uma imagem pequena para confirmar que Docker est� funcionando"]] },
  { id: 2, title: "Docker na pr�tica", subtitle: "Portas, logs, ciclo de vida e Dockerfile.", practice: "Containerize uma aplica��o simples e abra-a em localhost.", lessons: ["Executar e parar containers", "Ler logs e entrar no terminal", "Criar imagens com Dockerfile"], topics: [["-d", "deixa o container rodando em segundo plano"], ["docker logs", "mostra a sa�da produzida pelo container"], ["docker stop", "interrompe um container em execu��o"], ["Dockerfile", "descreve como montar uma imagem"], ["WORKDIR", "define a pasta de trabalho dentro da imagem"], ["COPY", "leva arquivos do projeto para a imagem"], ["CMD", "define o comando padr�o ao iniciar o container"], ["docker build", "cria uma imagem a partir do Dockerfile"], ["-p 3000:3000", "publica a porta 3000 do container na porta 3000 do computador"], ["tag", "identifica uma vers�o de imagem, como minha-app:1.0"]] },
  { id: 3, title: "Aplica��es com Docker", subtitle: "Volumes, redes, banco de dados e Docker Compose.", practice: "Suba uma API e PostgreSQL usando compose.yaml.", lessons: ["Persistir dados com volumes", "Conectar servi�os por rede", "Orquestrar com Compose"], topics: [["volume nomeado", "mant�m dados mesmo ap�s remover um container"], ["bind mount", "compartilha uma pasta do computador com o container"], ["rede Docker", "permite que containers conversem por nome"], ["localhost no container", "aponta para o pr�prio container"], ["compose.yaml", "declara os servi�os de uma aplica��o"], ["docker compose up", "cria e inicia os servi�os declarados"], ["depends_on", "organiza a ordem de in�cio entre servi�os"], ["environment", "define vari�veis de ambiente para um servi�o"], ["docker compose down", "para e remove os containers do projeto"], [".dockerignore", "evita enviar arquivos desnecess�rios ao build"]] },
  { id: 4, title: "Fundamentos de Kubernetes", subtitle: "Kind, kubectl, Pods, Deployments e labels.", practice: "Crie um cluster Kind e implante uma app com duas r�plicas.", lessons: ["Criar cluster local", "Declarar Pods e Deployments", "Usar labels e r�plicas"], topics: [["Kind", "cria um cluster Kubernetes local usando Docker"], ["kubectl", "� a ferramenta de linha de comando para controlar o cluster"], ["node", "executa Pods dentro do cluster"], ["Pod", "� a menor unidade de execu��o do Kubernetes"], ["Deployment", "mant�m a quantidade desejada de Pods"], ["replicas", "define quantas c�pias da aplica��o devem existir"], ["label", "� uma etiqueta usada para identificar recursos"], ["kubectl apply", "cria ou atualiza recursos declarados em YAML"], ["kubectl get pods", "lista os Pods do namespace atual"], ["YAML", "usa indenta��o com espa�os para organizar configura��es"]] },
  { id: 5, title: "Kubernetes em opera��o", subtitle: "Services, configura��o, escala, sa�de e atualiza��es.", practice: "Publique uma app, escale para tr�s r�plicas e execute um rollout.", lessons: ["Conectar com Services", "Configurar e proteger", "Escalar e observar"], topics: [["Service", "fornece um endere�o est�vel para acessar Pods"], ["selector", "liga um Service aos Pods com labels correspondentes"], ["ConfigMap", "guarda configura��es n�o sens�veis"], ["Secret", "guarda valores sens�veis que n�o devem ir para o c�digo"], ["readiness probe", "define quando um Pod pode receber tr�fego"], ["liveness probe", "detecta quando um container precisa reiniciar"], ["requests", "reservam recursos m�nimos para um container"], ["limits", "definem o m�ximo de recursos que um container pode usar"], ["rollout", "atualiza uma vers�o gradualmente"], ["kubectl scale", "altera a quantidade de r�plicas de um Deployment"]] },
  { id: 6, title: "Publica��o e projeto final", subtitle: "Ingress, persist�ncia, Helm, seguran�a e entrega.", practice: "Conclua o checklist do projeto final: app, banco, Compose e Kubernetes.", lessons: ["Publicar com Ingress", "Persistir dados", "Empacotar com Helm"], topics: [["Ingress", "declara regras para receber tr�fego HTTP e envi�-lo a Services"], ["controller de Ingress", "executa as regras definidas pelo Ingress"], ["PersistentVolumeClaim", "solicita armazenamento persistente para uma aplica��o"], ["StatefulSet", "� indicado quando r�plicas precisam de identidade est�vel"], ["Helm", "instala pacotes configur�veis chamados charts"], ["chart", "� um pacote de recursos Kubernetes"], ["release", "� uma instala��o de um chart no cluster"], ["namespace", "separa recursos dentro de um cluster"], ["RBAC", "controla quem pode executar a��es no Kubernetes"], ["projeto final", "re�ne Docker, Compose e Kubernetes em uma entrega pr�tica"]] },
];

export default function Home() {
  const [active, setActive] = useState(1); const [progress, setProgress] = useState<number[]>([]); const [practice, setPractice] = useState<number[]>([]); const [answers, setAnswers] = useState<Record<number, number>>({}); const [attempts, setAttempts] = useState<Record<number, number[]>>({}); const [signedIn, setSignedIn] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("container-lab-v2"); if (saved) { const s = JSON.parse(saved); setProgress(s.progress || []); setPractice(s.practice || []); setAttempts(s.attempts || {}); } }, []);
  useEffect(() => { localStorage.setItem("container-lab-v2", JSON.stringify({ progress, practice, attempts })); }, [progress, practice, attempts]);
  const module = modules[active - 1]; const unlocked = active === 1 || attempts[active - 1]?.some(score => score >= 70);
  const score = useMemo(() => module.topics.reduce((sum, _, i) => sum + (answers[i] === 0 ? 10 : 0), 0), [answers, module]);
  const completeAssessment = () => { setAttempts(prev => ({ ...prev, [active]: [...(prev[active] || []), score] })); setAnswers({}); };
  const passed = attempts[active]?.some(s => s >= 70); const overall = Math.round((attempts && modules.filter(m => attempts[m.id]?.some(s => s >= 70)).length / modules.length) * 100);
  return <main><header><a className="brand">&gt;_ container<span>lab</span></a><nav><a href="#trilha">Trilha</a><a href="#perfil">Perfil</a></nav><button className="login" onClick={() => setSignedIn(!signedIn)}>{signedIn ? "Conta de estudo" : "Entrar para salvar"}</button></header><section className="hero"><p className="eyebrow">CURSO PR�TICO PARA WINDOWS</p><h1>Aprenda Docker e Kubernetes <em>fazendo.</em></h1><p>Seis m�dulos guiados, pr�ticas reais e avalia��es para provar que voc� entendeu antes de avan�ar.</p><a className="cta" href="#trilha">Come�ar a trilha</a></section><section id="perfil" className="profile"><div><p className="eyebrow">SEU PROGRESSO</p><h2>{overall}% da trilha conclu�da</h2><p>{signedIn ? "Seu progresso est� associado a esta conta de estudo." : "Entre para sincronizar seu progresso em todos os dispositivos."}</p></div><div className="badges">{modules.map(m => <span className={attempts[m.id]?.some(s => s >= 70) ? "badge earned" : "badge"} key={m.id}>M{m.id}</span>)}</div></section><section id="trilha" className="course"><aside>{modules.map(m => <button key={m.id} disabled={m.id > 1 && !attempts[m.id - 1]?.some(s => s >= 70)} className={active === m.id ? "module active" : "module"} onClick={() => setActive(m.id)}><b>M�dulo {m.id}</b><span>{m.title}</span>{attempts[m.id]?.some(s => s >= 70) && <i>Aprovado</i>}</button>)}</aside><article className="lesson"><p className="eyebrow">M�DULO {module.id} DE 6</p><h2>{module.title}</h2><p className="lead">{module.subtitle}</p><h3>O que voc� vai dominar</h3><ul>{module.lessons.map(x => <li key={x}>{x}</li>)}</ul><div className="practice"><h3>Laborat�rio pr�tico</h3><p>{module.practice}</p><label><input type="checkbox" checked={practice.includes(active)} onChange={() => setPractice(p => p.includes(active) ? p.filter(x => x !== active) : [...p, active])}/> Conclu� esta pr�tica</label></div><h3>Avalia��o do m�dulo</h3><p className="hint">Responda as 10 quest�es. Voc� precisa de 70% e concluir a pr�tica para desbloquear o pr�ximo m�dulo.</p>{module.topics.map(([topic, definition], i) => <fieldset key={topic}><legend>{i + 1}. Qual afirma��o est� correta sobre <strong>{topic}</strong>?</legend>{[definition, "� uma configura��o que substitui qualquer outro recurso", "funciona apenas fora de containers"].map((choice, n) => <label key={choice}><input type="radio" name={`q${i}`} checked={answers[i] === n} onChange={() => setAnswers(a => ({ ...a, [i]: n }))}/>{choice}</label>)}</fieldset>)}<button className="cta" disabled={!practice.includes(active) || Object.keys(answers).length !== 10} onClick={completeAssessment}>Finalizar avalia��o</button>{attempts[active]?.length > 0 && <div className={passed ? "result success" : "result"}><strong>�ltima nota: {attempts[active].at(-1)}%</strong><p>{passed ? "M�dulo aprovado. A pr�xima etapa foi desbloqueada e sua badge foi concedida." : "Revise as aulas e tente novamente. As tentativas s�o ilimitadas."}</p></div>}</article></section></main>;
}
