export type QuizQuestion = { prompt: string; options: string[]; answer: number; explanation: string };

export type CourseModule = {
  id: number;
  title: string;
  subtitle: string;
  objective: string;
  practice: string;
  lessons: string[];
  questions: QuizQuestion[];
};

const q = (prompt: string, options: string[], answer: number, explanation: string): QuizQuestion => ({ prompt, options, answer, explanation });

export const courseModules: CourseModule[] = [
  { id: 1, title: "Ambiente e fundamentos", subtitle: "Windows, WSL 2 e seu primeiro container", objective: "Preparar um ambiente seguro e entender imagens e containers.", practice: "Execute docker run hello-world no PowerShell e confirme a mensagem final.", lessons: ["Windows e PowerShell", "WSL 2", "Docker Desktop"], questions: [
    q("O que é uma imagem Docker?", ["Molde imutável", "Container em execução", "Banco de dados", "Editor"], 0, "Imagem é modelo usado para criar containers."), q("Qual comando executa imagem de teste?", ["docker test", "docker run hello-world", "docker start image", "kubectl run"], 1, "docker run cria e executa container."), q("Docker Desktop precisa estar?", ["Fechado", "Aberto e iniciado", "Instalado no WSL somente", "No navegador"], 1, "Motor Docker precisa estar em execução."), q("Container é?", ["Uma imagem parada", "Instância de imagem", "Arquivo YAML", "Conta Docker"], 1, "Container é execução isolada de uma imagem."), q("WSL 2 oferece?", ["Kernel Linux no Windows", "Outro navegador", "Cluster remoto", "Antivírus"], 0, "WSL 2 permite ambiente Linux integrado."), q("Onde executar comandos no Windows?", ["PowerShell", "Bloco de notas", "Explorer", "BIOS"], 0, "PowerShell é terminal indicado."), q("Registry serve para?", ["Guardar imagens", "Guardar senhas", "Criar Pods", "Editar YAML"], 0, "Registries distribuem imagens."), q("Qual verifica Docker instalado?", ["docker --version", "docker check", "docker ready", "docker open"], 0, "Mostra versão do cliente."), q("Imagem muda quando container escreve dados?", ["Sempre", "Não", "Só no Windows", "Só com WSL"], 1, "Dados do container não alteram imagem."), q("Primeiro erro a checar?", ["Docker Desktop desligado", "Neon", "GitHub", "Vercel"], 0, "Confirme motor Docker antes."),
  ] },
  { id: 2, title: "Docker na prática", subtitle: "Portas, logs, ciclo de vida e Dockerfile", objective: "Executar e construir aplicações em containers.", practice: "Containerize uma aplicação simples com Dockerfile e abra em localhost.", lessons: ["Portas e logs", "Ciclo de vida", "Dockerfile"], questions: [
    q("-p 8080:80 significa?", ["Windows 8080 para container 80", "Duas portas Windows", "Duas imagens", "Porta bloqueada"], 0, "Primeira porta é host; segunda é container."), q("Logs de container?", ["docker logs NOME", "docker image logs", "kubectl logs", "docker build logs"], 0, "docker logs lê saída do container."), q("Dockerfile é?", ["Receita de imagem", "Container rodando", "Senha", "Volume"], 0, "Dockerfile descreve build."), q("CMD define?", ["Comando inicial", "Porta externa", "Volume", "Registry"], 0, "CMD é comando padrão de início."), q("docker ps mostra?", ["Containers ativos", "Imagens", "Volumes", "Nodes"], 0, "docker ps lista containers em execução."), q("docker stop faz?", ["Para container", "Apaga imagem", "Cria rede", "Publica porta"], 0, "Interrompe execução."), q("Tag de imagem ajuda?", ["Versionar build", "Abrir porta", "Criar volume", "Ler logs"], 0, "Tags identificam versões."), q("EXPOSE publica porta?", ["Não sozinho", "Sempre", "Só no Windows", "Só com Compose"], 0, "Use -p para publicar."), q("docker build cria?", ["Imagem", "Pod", "Secret", "Cluster"], 0, "Build produz imagem."), q("--rm é útil porque?", ["Remove container ao terminar", "Remove imagem", "Remove volume", "Remove Docker"], 0, "Evita containers descartáveis acumulados."),
  ] },
  { id: 3, title: "Aplicações com Docker", subtitle: "Volumes, redes, Compose e PostgreSQL", objective: "Orquestrar serviços locais com dados persistentes.", practice: "Suba API e PostgreSQL usando compose.yaml.", lessons: ["Volumes", "Redes", "Docker Compose"], questions: [
    q("Volume Docker guarda?", ["Dados persistentes", "Senhas Clerk", "Código Git", "Pods"], 0, "Volume sobrevive ao container."), q("Rede Docker permite?", ["Serviços conversarem", "Criar imagem", "Criar cluster", "Fazer deploy"], 0, "Rede isola comunicação."), q("Compose usa?", ["compose.yaml", "Dockerfile obrigatório", "package.json", "ingress.yaml"], 0, "Compose descreve serviços."), q("docker compose up faz?", ["Inicia serviços", "Apaga dados", "Cria Git", "Instala WSL"], 0, "Sobe stack declarada."), q("PostgreSQL deve usar?", ["Volume", "Só memória", "Imagem custom sempre", "Ingress"], 0, "Banco precisa persistir dados."), q("Nome de serviço na rede vira?", ["Hostname interno", "Senha", "Tag", "Porta host"], 0, "Containers resolvem nome do serviço."), q("docker compose down remove volume nomeado?", ["Não por padrão", "Sempre", "Só Windows", "Só Kubernetes"], 0, "Volumes ficam sem -v."), q("depends_on garante banco pronto?", ["Não", "Sempre", "Só com WSL", "Só Postgres"], 0, "Organiza início, não health."), q("Segredo deve entrar na imagem?", ["Não", "Sempre", "Só produção", "Só Compose"], 0, "Use variáveis seguras."), q("Banco exposto ao host precisa?", ["Port mapping", "Ingress", "Helm", "Pod"], 0, "Portas conectam host ao container."),
  ] },
  { id: 4, title: "Fundamentos de Kubernetes", subtitle: "Kind, kubectl, Pods e Deployments", objective: "Criar cluster local e implantar aplicação declarativa.", practice: "Implante aplicação com duas réplicas no Kind.", lessons: ["Kind e kubectl", "Pods", "Deployments e labels"], questions: [
    q("Kind cria?", ["Cluster Kubernetes local", "Imagem Docker", "Banco Neon", "Conta Clerk"], 0, "Kind executa Kubernetes em Docker."), q("kubectl é?", ["Cliente do cluster", "Banco", "Container", "Registry"], 0, "kubectl conversa com API Kubernetes."), q("Pod é?", ["Menor unidade executável", "Imagem", "Domínio", "Usuário"], 0, "Pod hospeda containers."), q("Deployment mantém?", ["Estado desejado", "Senha", "Volume local", "DNS externo"], 0, "Deployment cria e repõe Pods."), q("Labels servem para?", ["Selecionar recursos", "Criptografar", "Criar imagem", "Fazer login"], 0, "Labels conectam recursos."), q("kubectl get nodes mostra?", ["Nós do cluster", "Imagens", "Arquivos", "Usuários"], 0, "Nodes executam Pods."), q("Replicas: 2 pede?", ["Dois Pods", "Dois clusters", "Duas imagens", "Dois volumes"], 0, "Deployment mantém duas cópias."), q("YAML usa?", ["Espaços", "Tabs obrigatórios", "Somente JSON", "Senha"], 0, "Indentação por espaços importa."), q("Pod apagado com Deployment?", ["É recriado", "Some para sempre", "Apaga cluster", "Vira imagem"], 0, "Controlador reconcilia estado."), q("Contexto kubectl define?", ["Cluster alvo", "Senha", "Imagem", "Volume"], 0, "Evita comandos no cluster errado."),
  ] },
  { id: 5, title: "Kubernetes em operação", subtitle: "Services, configuração, escala e saúde", objective: "Expor, configurar e atualizar aplicação com segurança.", practice: "Publique Service e faça rollout de uma nova versão.", lessons: ["Services", "ConfigMaps e Secrets", "Rollouts e probes"], questions: [
    q("Service fornece?", ["Endereço estável", "Imagem", "Cluster novo", "Senha"], 0, "Service seleciona Pods."), q("ConfigMap guarda?", ["Configuração não sensível", "Senha secreta", "Imagem", "Histórico Git"], 0, "Use para valores comuns."), q("Secret é criptografia garantida?", ["Não", "Sim", "Só no Neon", "Só no Windows"], 0, "Base64 não é criptografia."), q("Readiness decide?", ["Se Pod recebe tráfego", "Se imagem baixa", "Se volume apaga", "Se usuário loga"], 0, "Pod pronto entra no Service."), q("Liveness detecta?", ["Processo travado", "Domínio", "Tag", "Conta"], 0, "Pode reiniciar container."), q("Rollout status acompanha?", ["Atualização", "Build Docker", "Banco", "Login"], 0, "Mostra progresso do Deployment."), q("kubectl scale altera?", ["Réplicas", "Imagem", "Secret", "Node versão"], 0, "Escala quantidade de Pods."), q("Resource limit define?", ["Teto de recurso", "DNS", "Porta", "Usuário"], 0, "Limita CPU/memória."), q("Selector de Service deve combinar?", ["Labels do Pod", "Nome do arquivo", "Senha", "Tag Git"], 0, "Sem match não há endpoints."), q("rollout undo faz?", ["Volta versão", "Apaga banco", "Para cluster", "Cria volume"], 0, "Reverte Deployment."),
  ] },
  { id: 6, title: "Publicação e projeto final", subtitle: "Ingress, persistência, Helm e segurança", objective: "Entregar projeto com checklist e operação básica.", practice: "Conclua checklist: Ingress, persistência, Helm e documentação.", lessons: ["Ingress", "Persistência", "Helm e entrega"], questions: [
    q("Ingress precisa de?", ["Controller", "Dockerfile", "Clerk", "WSL desligado"], 0, "Regra sem controller não funciona."), q("PVC pede?", ["Armazenamento persistente", "Imagem", "Usuário", "Domínio"], 0, "Claim solicita storage."), q("Helm chart é?", ["Pacote Kubernetes", "Container", "Banco", "Secret"], 0, "Chart agrupa manifestos configuráveis."), q("Helm release é?", ["Instalação de chart", "Imagem", "Usuário", "Node"], 0, "Release identifica instalação."), q("Ingress normalmente ajuda com?", ["Roteamento HTTP", "Build imagem", "Criar volume", "Rodar SQL"], 0, "Encaminha tráfego a Services."), q("Projeto final deve ter?", ["README e checklist", "Senha no Git", "Tag latest apenas", "Sem logs"], 0, "Documentação torna entrega reproduzível."), q("Backup é necessário para?", ["Dados persistentes", "CSS", "Labels", "Pods descartáveis"], 0, "Volumes não substituem backup."), q("Secret deve ir ao Git?", ["Nunca", "Sempre", "Só produção", "Só Helm"], 0, "Use cofre de segredos."), q("Imagem fixa melhora?", ["Reprodutibilidade", "Quantidade de Pods", "Domínio", "Login"], 0, "Tag explícita evita mudanças invisíveis."), q("Antes de publicar, confirmar?", ["Probes e acesso", "Só cor do site", "Só nome Pod", "Só Git"], 0, "Verifique saúde e rota."),
  ] },
];

export const getCourseModule = (id: number) => courseModules.find((item) => item.id === id);
